# Generated by Django 3.2.9 on 2021-11-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettory_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_pot', models.IntegerField()),
                ('drow_time', models.DateTimeField(auto_now_add=True)),
                ('round', models.IntegerField()),
                ('drawn_last_time', models.EmailField(max_length=254, unique=True)),
                ('winning_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lettory_api.tickets'),
        ),
    ]
